
export const icon={
    hat:require('../icons/hat.png'),
    ai:require('../icons/ai.png'),
    appinventiv:require('../icons/appinventiv.png'),
    intro_1:require('../icons/intro_1.png'),
    intro_2:require('../icons/intro_2.png'),
    intro_3:require('../icons/intro_3.png'),
    sign_in:require('../icons/sign_in.png'),
    signup:require('../icons/signup.png'),
    eye:require('../icons/eye.png'),
    eyecut:require('../icons/eyecut.png'),
    email:require('../icons/email.png'),
    github:require('../icons/github.png'),
    google:require('../icons/google.png'),
    pass:require('../icons/pass.png'),
    account:require('../icons/account.png'),
    otp:require('../icons/otp.png'),
    forgot:require('../icons/forgot.png'),
    home:require('../icons/home.png'),
    search:require('../icons/search.png'),
    profile:require('../icons/profile.png'),
    courses:require('../icons/courses.png'),
    userr:require('../icons/userr.png'),
    bag:require('../icons/bag.png'),
    search1:require('../icons/search1.png'),
    1:require('../icons/1.jpg'),
    2:require('../icons/2.webp'),
    3:require('../icons/3.webp'),
    4:require('../icons/4.webp'),

}